### ISSUE TITLE
TODO statuses

### ISSUE THREAD

**Issue by ctindall** [ctindall/org-blog#3]
- [x] Properly parse TODO statuses
- [x] provide them to the template context
- [x] add configuration option to render/not render posts based on TODO status
